#!/bin/bash
"$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
cd ../../..

echo "Welcome to Agile Toolkit. Running 'php -S localhost:8888' in `pwd`"
echo

(sleep 1 && open http://localhost:8888) &
php -S localhost:8888
